"use client";

import * as React from "react";

type Language = "en" | "es" | "sv";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const LanguageContext = React.createContext<LanguageContextValue | null>(null);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.menu": "Menu",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "nav.story": "Our Story",
    "nav.book": "Book a Table",
    "nav.event": "Book an Event",
    "hero.badge": "Fine Dining Experience",
    "hero.title.line1": "When laughter and good mood create an unforgettable",
    "hero.title.line2": "memory",
    "hero.subtitle":
      "Experience culinary excellence in an atmosphere of refined elegance",
    "hero.cta.menu": "View Menu",
    "hero.cta.about": "Learn More",
    "about.badge": "About Us",
    "about.story": "Our Story",
    "about.paragraph1":
      "Welcome to our Swedish restaurant Grottan la Cueva. Everything here is made from scratch with care, love and deep respect for the ingredients. We serve Swedish traditional food of the highest quality, rich in flavor and above all with sauces at the center, just as we think it should taste. Warm welcome 💛",
    "about.paragraph2": "",
    "about.feature.experience.title": "Enjoy every bite",
    "about.feature.experience.desc": "",
    "about.feature.team.title": "Passionate team",
    "about.feature.team.desc": "",
    "about.feature.michelin.title": "Quality without pretension",
    "about.feature.michelin.desc": "",
    "story.title": "Our Story",
    "story.subtitle.part1":
      "We've been best friends for over ten years and have previously worked together — though in very different industries. What truly connects us is our shared drive to always do things better. So when the opportunity came to create a different, personal, and genuinely fun restaurant in Alicante, we didn't hesitate. Because great food is never just about what's on the plate. It's about warmth, atmosphere, and feeling at home.",
    "story.subtitle.part2":
      "As passionate food creators, we share a special Scandinavian love for sauces — the kind that elevate classic meat, fish, and desserts. Everything is prepared from scratch using the highest-quality ingredients. We don't cut corners. Because when flavor and laughter come together, that's the best recipe of all.",
    "menu.badge": "Our Menu",
    "menu.title.line1": "Exquisite",
    "menu.title.line2": "Dishes",
    "menu.subtitle":
      "Discover our signature dishes, crafted with love and mastery",
    "menu.filter.all": "All",
    "menu.filter.entradas": "Starters",
    "menu.filter.platoPrincipal": "Main Course",
    "menu.filter.postres": "Desserts",
    "menu.item.ribeye.name": "Ribeye Steak",
    "menu.item.ribeye.desc": "Premium beef with red wine sauce and truffle oil",
    "menu.item.foto1.name": "El Secreto de la Cueva",
    "menu.item.foto1.desc":
      "Iberico flank steak with béarnaise and your choice of potatoes.\nGratin or wedges",
    "menu.signature": "Signature",
    "menu.item.foto5.name": "Gravlax",
    "menu.item.foto5.desc": "Gravlax with dill-stewed potatoes",
    "menu.item.food9.name": "Meatballs with juniper and cream sauce",
    "menu.item.food9.desc":
      "Homemade meatballs with juniper cream sauce,\nlingonberries and mashed potatoes",
    "menu.item.food10.name": "Tasting plate",
    "menu.item.food10.desc": "Tapas of starters and various hot dishes with sauces",
    "menu.item.pasta.name": "Seafood Pasta",
    "menu.item.pasta.desc": "Homemade pasta with tiger prawns, mussels and calamari",
    "menu.item.foto2.name": "Lamb meatball patties",
    "menu.item.foto2.desc":
      "Lamb mince patties stuffed with feta, served with potato wedges and tzatziki",
    "menu.item.foto6.name": "Cloudberry with almond cake",
    "menu.item.foto6.desc":
      "Cloudberry jam with Spanish almond cake in rum,\nserved with whipped cream",
    "menu.item.salmon.name": "Salmon Tartare",
    "menu.item.salmon.desc": "Fresh salmon tartare with avocado and caviar",
    "menu.item.foto7.name": "Gravlaxtoast",
    "menu.item.foto7.desc": "Gravlaxtoast with mustard-dill sauce",
    "menu.item.foto8.name": "Skagen",
    "menu.item.foto8.desc": "Toast Skagen with Nordic prawns",
    "menu.item.foto3.name": "Wallenbergare",
    "menu.item.foto3.desc":
      "Wallenbergare with mashed potatoes, lingonberries, peas, and browned butter",
    "menu.item.chocolate.name": "Crumble with vanilla sauce",
    "menu.item.chocolate.desc":
      "Classic crumble with summer berries and\nhomemade vanilla sauce",
    "menu.cta": "View Full Menu",
    "menu.cta.less": "Show Less",
    "reviews.title": "Our reviews",
    "reviews.subtitle": "Guests share their experience with us",
    "reviews.viewThisReview": "Review on Google",
    "reviews.starsAria": "5 out of 5 stars",
    "reviews.author.james": "James M.",
    "reviews.author.guest": "Hana Cimperman",
    "reviews.author.urszula": "Urszula",
    "reviews.quote.guest":
      "The hosts are absolutely amazing! They have such a warm and hospitable energy. They welcomed us with some of their traditional Swedish dishes, and afterwards we enjoyed classic karaoke with ABBA. We're definitely looking forward to visiting again! ☺️",
    "reviews.quote.james":
      "Fantastic restaurant/wine bar right in the centre of Alicante, came here multiple times during our stay here. Such a relaxed atmosphere complimented by very welcoming entertaining hosts. Dined here on our final night and it was amazing.. traditional tasty Swedish food and plenty of wine. Would definitely recommend to anyone in the area!",
    "reviews.quote.urszula":
      "The best bar in Alicante, delicious food and drinks at reasonable prices. The atmosphere is wonderful — you don't want to leave the place, such lovely people spreading positive energy. Highly recommended and we'll definitely be back here 🫶🏼🙌",
    "gallery.badge": "Gallery",
    "gallery.title.line1": "Take a look at",
    "gallery.title.line2": "our world",
    "gallery.subtitle": "Atmosphere, taste, and beauty in every frame",
    "gallery.filter.all": "All",
    "gallery.filter.food": "Food",
    "gallery.filter.interior": "Interior",
    "gallery.filter.team": "Team",
    "contact.badge": "Reserve a Table",
    "contact.subtitle": "Reserve your table and enjoy an unforgettable evening",
    "contact.form.title": "Reservation Form",
    "contact.form.name": "Your Name",
    "contact.form.email": "Email",
    "contact.form.phone": "Phone",
    "contact.form.date": "Date",
    "contact.form.time": "Time",
    "contact.form.guests": "Number of Guests",
    "contact.form.guest": "Guest",
    "contact.form.guestsPlural": "Guests",
    "contact.form.submit": "Reserve Table",
    "contact.form.selectPlaceholder": "Select…",
    "contact.toast": "Reservation submitted! We will contact you shortly.",
    "contact.toastError": "Could not send reservation. Please try again or call us.",
    "events.form.title": "Book an Event",
    "events.form.name": "Your Name",
    "events.form.email": "Email",
    "events.form.phone": "Phone",
    "events.form.date": "Date",
    "events.form.time": "Time",
    "events.form.guests": "Number of Guests",
    "events.form.type": "Event Type",
    "events.form.type.private": "Private Dinner",
    "events.form.type.birthday": "Birthday",
    "events.form.type.corporate": "Corporate",
    "events.form.message": "Message",
    "events.form.submit": "Send Event Request",
    "events.form.messageEmpty": "(No message)",
    "events.toast": "Event request submitted! We will contact you shortly.",
    "events.toastError": "Could not send event request. Please try again or call us.",
    "contact.info.address.title": "Address",
    "contact.info.address.content": "Calle Artilleros 3 03002 Alicante, Spain",
    "contact.info.phone.title": "Phone",
    "contact.info.phone.content": "+34 604 12 70 64",
    "contact.info.email.title": "Email",
    "contact.info.email.content": "lacueva708@gmail.com",
    "contact.info.hours.title": "Hours",
    "contact.info.hours.content":
      "Mon–Fri: 18:00–01:30\nSat–Sun: 14:00–01:30",
    "contact.map": "Location Map",
    "footer.tagline": "Enjoy good food, right in the city",
    "footer.section.about": "About",
    "footer.section.services": "Services",
    "footer.section.contact": "Contact",
    "footer.link.history": "Our History",
    "footer.link.team": "Our Story",
    "footer.link.careers": "Careers",
    "footer.link.menu": "Menu",
    "footer.link.gallery": "Gallery",
    "footer.link.reservations": "Reservations",
    "footer.link.events": "Events",
    "footer.link.privacy": "Privacy Policy",
    "footer.link.terms": "Terms of Service",
    "footer.rights": "All rights reserved.",
    "ui.scrollToTop": "Back to top",
    "ui.languageToggle": "Change language",
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Sobre",
    "nav.menu": "Menú",
    "nav.gallery": "Galería",
    "nav.contact": "Contacto",
    "nav.story": "Nuestra historia",
    "nav.book": "Reservar mesa",
    "nav.event": "Reservar evento",
    "hero.badge": "Experiencia de alta cocina",
    "hero.title.line1": "Cuando la risa y el buen humor crean un recuerdo",
    "hero.title.line2": "inolvidable",
    "hero.subtitle":
      "Vive la excelencia culinaria en un ambiente de elegancia refinada",
    "hero.cta.menu": "Ver menú",
    "hero.cta.about": "Saber más",
    "about.badge": "Sobre nosotros",
    "about.story": "Nuestra historia",
    "about.paragraph1":
      "Bienvenido a nuestro restaurante sueco Grottan la Cueva. Aquí todo se prepara desde cero con cuidado, amor y profundo respeto por los ingredientes. Servimos comida tradicional sueca de la más alta calidad, rica en sabor y sobre todo con salsas en el centro, tal como creemos que debe saber. Bienvenido 💛",
    "about.paragraph2":
      "Cada visita es un momento para bajar el ritmo, disfrutar del ambiente y sentirse cómodo. Un lugar para buen ánimo, buena comida y tiempo bien aprovechado.",
    "about.feature.experience.title": "Disfruta cada bocado",
    "about.feature.experience.desc": "",
    "about.feature.team.title": "Equipo apasionado",
    "about.feature.team.desc": "",
    "about.feature.michelin.title": "Calidad sin pretensiones",
    "about.feature.michelin.desc": "",
    "story.title": "Nuestra historia",
    "story.subtitle.part1":
      "Hemos sido mejores amigos durante más de diez años y hemos trabajado juntos antes, aunque en industrias muy diferentes. Lo que nos une es nuestra motivación compartida de hacer siempre las cosas mejor. Cuando surgió la oportunidad de crear un restaurante diferente, personal y genuinamente divertido en Alicante, no dudamos. Porque la buena comida nunca es solo lo que hay en el plato. Se trata de calidez, ambiente y sentirse como en casa.",
    "story.subtitle.part2":
      "Como apasionados creadores de comida, compartimos un amor escandinavo especial por las salsas, lo que realza la carne, el pescado y los postres clásicos. Todo se prepara desde cero con ingredientes de la más alta calidad. No se puede hacer trampa con la comida con nosotros, porque cuando el sabor y la risa se encuentran, ahí está la mejor receta.",
    "menu.badge": "Nuestro menú",
    "menu.title.line1": "Platos",
    "menu.title.line2": "Exquisitos",
    "menu.subtitle": "Descubre nuestros platos exclusivos, hechos con amor y maestría",
    "menu.filter.all": "Todo",
    "menu.filter.entradas": "Entradas",
    "menu.filter.platoPrincipal": "Plato principal",
    "menu.filter.postres": "Postres",
    "menu.item.ribeye.name": "Bistec Ribeye",
    "menu.item.ribeye.desc":
      "Carne premium con salsa de vino tinto y aceite de trufa",
    "menu.item.foto1.name": "El Secreto de la Cueva",
    "menu.item.foto1.desc":
      "El Secreto de la Cueva con salsa bearnesa y patata a elección.\nGratinada o gajos",
    "menu.signature": "Especialidad",
    "menu.item.foto5.name": "Gravlax",
    "menu.item.foto5.desc": "Gravlax con patatas al eneldo",
    "menu.item.food9.name": "Albóndigas suecas con salsa de enebro y nata",
    "menu.item.food9.desc":
      "Albóndigas caseras con salsa de nata de enebro,\narándanos rojos y puré de patatas",
    "menu.item.food10.name": "Plato de degustación",
    "menu.item.food10.desc": "Tapas de entradas y varios calientes con salsas",
    "menu.item.pasta.name": "Pasta de mariscos",
    "menu.item.pasta.desc":
      "Pasta casera con langostinos, mejillones y calamar",
    "menu.item.foto2.name": "Albóndigas de cordero",
    "menu.item.foto2.desc":
      "Albóndigas de cordero rellenas de feta, con patatas gajo y tzatziki",
    "menu.item.foto6.name": "Mora ártica con bizcocho de almendra",
    "menu.item.foto6.desc":
      "Mermelada de mora ártica con bizcocho de almendra al ron,\ncon nata montada",
    "menu.item.salmon.name": "Tartar de salmón",
    "menu.item.salmon.desc": "Salmón fresco con aguacate y caviar",
    "menu.item.foto7.name": "Gravlaxtoast",
    "menu.item.foto7.desc": "Gravlaxtoast con salsa de mostaza y eneldo",
    "menu.item.foto8.name": "Skagen",
    "menu.item.foto8.desc": "Toast Skagen con gambas nórdicas",
    "menu.item.foto3.name": "Wallenbergare",
    "menu.item.foto3.desc":
      "Wallenbergare con puré de patata, arándanos rojos, guisantes y mantequilla avellanada",
    "menu.item.chocolate.name": "Crumble con salsa de vainilla",
    "menu.item.chocolate.desc":
      "Crumble clásico con bayas de verano y\nsalsa de vainilla casera",
    "menu.cta": "Ver menú completo",
    "menu.cta.less": "Ver menos",
    "reviews.title": "Reseñas",
    "reviews.subtitle": "Nuestros clientes comparten su experiencia.",
    "reviews.viewThisReview": "Reseña en Google",
    "reviews.starsAria": "5 de 5 estrellas",
    "reviews.author.james": "James M.",
    "reviews.author.guest": "Hana Cimperman",
    "reviews.author.urszula": "Urszula",
    "reviews.quote.guest":
      "The hosts are absolutely amazing! They have such a warm and hospitable energy. They welcomed us with some of their traditional Swedish dishes, and afterwards we enjoyed classic karaoke with ABBA. We're definitely looking forward to visiting again! ☺️",
    "reviews.quote.james":
      "Fantastic restaurant/wine bar right in the centre of Alicante, came here multiple times during our stay here. Such a relaxed atmosphere complimented by very welcoming entertaining hosts. Dined here on our final night and it was amazing.. traditional tasty Swedish food and plenty of wine. Would definitely recommend to anyone in the area!",
    "reviews.quote.urszula":
      "The best bar in Alicante, delicious food and drinks at reasonable prices. The atmosphere is wonderful — you don't want to leave the place, such lovely people spreading positive energy. Highly recommended and we'll definitely be back here 🫶🏼🙌",
    "gallery.badge": "Galería",
    "gallery.title.line1": "Echa un vistazo a",
    "gallery.title.line2": "nuestro mundo",
    "gallery.subtitle": "Atmósfera, sabor y belleza en cada imagen",
    "gallery.filter.all": "Todo",
    "gallery.filter.food": "Comida",
    "gallery.filter.interior": "Interior",
    "gallery.filter.team": "Equipo",
    "contact.badge": "Reserva una mesa",
    "contact.subtitle": "Reserva tu mesa y disfruta de una noche inolvidable",
    "contact.form.title": "Formulario de reserva",
    "contact.form.name": "Tu nombre",
    "contact.form.email": "Correo",
    "contact.form.phone": "Teléfono",
    "contact.form.date": "Fecha",
    "contact.form.time": "Hora",
    "contact.form.guests": "Número de invitados",
    "contact.form.guest": "Invitado",
    "contact.form.guestsPlural": "Invitados",
    "contact.form.submit": "Reservar mesa",
    "contact.form.selectPlaceholder": "Seleccionar…",
    "contact.toast": "¡Reserva enviada! Nos pondremos en contacto pronto.",
    "contact.toastError": "No se pudo enviar la reserva. Inténtalo de nuevo o llámanos.",
    "events.form.title": "Reservar evento",
    "events.form.name": "Tu nombre",
    "events.form.email": "Correo",
    "events.form.phone": "Teléfono",
    "events.form.date": "Fecha",
    "events.form.time": "Hora",
    "events.form.guests": "Número de invitados",
    "events.form.type": "Tipo de evento",
    "events.form.type.private": "Cena privada",
    "events.form.type.birthday": "Cumpleaños",
    "events.form.type.corporate": "Corporativo",
    "events.form.message": "Mensaje",
    "events.form.submit": "Enviar solicitud",
    "events.form.messageEmpty": "(Sin mensaje)",
    "events.toast": "¡Solicitud enviada! Nos pondremos en contacto pronto.",
    "events.toastError": "No se pudo enviar la solicitud. Inténtalo de nuevo o llámanos.",
    "contact.info.address.title": "Dirección",
    "contact.info.address.content": "Calle Artilleros 3 03002 Alicante, España",
    "contact.info.phone.title": "Teléfono",
    "contact.info.phone.content": "+34 604 12 70 64",
    "contact.info.email.title": "Correo",
    "contact.info.email.content": "lacueva708@gmail.com",
    "contact.info.hours.title": "Horario",
    "contact.info.hours.content":
      "Lun–vie: 18:00–01:30\nSáb–dom: 14:00–01:30",
    "contact.map": "Mapa de ubicación",
    "footer.tagline": "Disfruta buena comida, justo en la ciudad",
    "footer.section.about": "Sobre",
    "footer.section.services": "Servicios",
    "footer.section.contact": "Contacto",
    "footer.link.history": "Nuestra historia",
    "footer.link.team": "Nuestra historia",
    "footer.link.careers": "Carreras",
    "footer.link.menu": "Menú",
    "footer.link.gallery": "Galería",
    "footer.link.reservations": "Reservas",
    "footer.link.events": "Eventos",
    "footer.link.privacy": "Política de privacidad",
    "footer.link.terms": "Términos de servicio",
    "footer.rights": "Todos los derechos reservados.",
    "ui.scrollToTop": "Volver arriba",
    "ui.languageToggle": "Cambiar idioma",
  },
  sv: {
    "nav.home": "Hem",
    "nav.about": "Om",
    "nav.menu": "Meny",
    "nav.gallery": "Galleri",
    "nav.contact": "Kontakt",
    "nav.story": "Vår historia",
    "nav.book": "Boka bord",
    "nav.event": "Boka event",
    "hero.badge": "Fine dining‑upplevelse",
    "hero.title.line1": "När god smak möter",
    "hero.title.line2": "glädje",
    "hero.subtitle":
      "Upplev kulinarisk excellens i en elegant atmosfär",
    "hero.cta.menu": "Se meny",
    "hero.cta.about": "Läs mer",
    "about.badge": "Om oss",
    "about.story": "Vår historia",
    "about.paragraph1":
      "Välkommen till vår svenska restaurang Grottan la Cueva. Här lagas allt från grunden med omsorg, kärlek och djup respekt för råvarorna. Vi serverar svensk traditionell mat av högsta kvalitet, rik på smak och framför allt med såser i centrum, precis som vi tycker att det ska smaka. Varmt välkommen 💛",
    "about.paragraph2": "",
    "about.feature.experience.title": "Njut av varje tugga",
    "about.feature.experience.desc": "",
    "about.feature.team.title": "Passionerat team",
    "about.feature.team.desc": "",
    "about.feature.michelin.title": "Kvalitet utan pretentioner",
    "about.feature.michelin.desc": "",
    "menu.badge": "Vår meny",
    "menu.title.line1": "Utsökta",
    "menu.title.line2": "Rätter",
    "menu.subtitle": "Upptäck våra signaturrätter, lagade med kärlek",
    "menu.filter.all": "Alla",
    "menu.filter.entradas": "Förrätter",
    "menu.filter.platoPrincipal": "Huvudrätt",
    "menu.filter.postres": "Efterrätter",
    "menu.item.ribeye.name": "Ribeye‑stek",
    "menu.item.ribeye.desc": "Premiumbiff med rödvinssås och tryffelolja",
    "menu.item.foto1.name": "El Secreto de la Cueva",
    "menu.item.foto1.desc":
      "Iberisk flankstek med bearnaisesås och valfri potatis.\nGratäng eller klyftpotatis",
    "menu.signature": "Signatur",
    "menu.item.foto5.name": "Gravlax",
    "menu.item.foto5.desc": "Gravad lax med dillstuvad potatis",
    "menu.item.food9.name": "Köttbullar med gräddsås",
    "menu.item.food9.desc":
      "Hemlagade köttbullar med gräddsås,\nlingon och potatismos",
    "menu.item.food10.name": "Smakprovs tallrik",
    "menu.item.food10.desc": "Tapas av förrätter och olika varma rätter med såser",
    "menu.item.pasta.name": "Skaldjurspasta",
    "menu.item.pasta.desc": "Hemlagad pasta med räkor, musslor och bläckfisk",
    "menu.item.foto2.name": "Lammfärs järpar",
    "menu.item.foto2.desc":
      "Lammfärs järpar fyllda med feta och klyftpotatis och tzatziki",
    "menu.item.foto6.name": "Hjortron med mandelkaka",
    "menu.item.foto6.desc":
      "Hjortronsylt med spansk mandelkaka i rom\nmed vispgrädde",
    "menu.item.salmon.name": "Lax­tartar",
    "menu.item.salmon.desc": "Färsk lax med avokado och kaviar",
    "menu.item.foto7.name": "Gravlaxtoast",
    "menu.item.foto7.desc": "Gravlaxtoast med hovmästarsås",
    "menu.item.foto8.name": "Skagen",
    "menu.item.foto8.desc": "Toast Skagen med nordiska räkor",
    "menu.item.foto3.name": "Wallenbergare",
    "menu.item.foto3.desc":
      "Wallenbergare med potatispuré, lingon, ärtor och brynt smör",
    "menu.item.chocolate.name": "Smulpaj med äkta vaniljsås",
    "menu.item.chocolate.desc":
      "Klassisk smulpaj med sommarbär och\nhemgjord äkta vaniljsås",
    "menu.cta": "Se hela menyn",
    "menu.cta.less": "Visa mindre",
    "reviews.title": "Omdömen",
    "reviews.subtitle": "Gäster delar sin upplevelse med oss.",
    "reviews.viewThisReview": "Omdöme på Google",
    "reviews.starsAria": "5 av 5 stjärnor",
    "reviews.author.james": "James M.",
    "reviews.author.guest": "Hana Cimperman",
    "reviews.author.urszula": "Urszula",
    "reviews.quote.guest":
      "The hosts are absolutely amazing! They have such a warm and hospitable energy. They welcomed us with some of their traditional Swedish dishes, and afterwards we enjoyed classic karaoke with ABBA. We're definitely looking forward to visiting again! ☺️",
    "reviews.quote.james":
      "Fantastic restaurant/wine bar right in the centre of Alicante, came here multiple times during our stay here. Such a relaxed atmosphere complimented by very welcoming entertaining hosts. Dined here on our final night and it was amazing.. traditional tasty Swedish food and plenty of wine. Would definitely recommend to anyone in the area!",
    "reviews.quote.urszula":
      "The best bar in Alicante, delicious food and drinks at reasonable prices. The atmosphere is wonderful — you don't want to leave the place, such lovely people spreading positive energy. Highly recommended and we'll definitely be back here 🫶🏼🙌",
    "gallery.badge": "Galleri",
    "gallery.title.line1": "Ta en titt på",
    "gallery.title.line2": "vår värld",
    "gallery.subtitle": "Atmosfär, smak och skönhet i varje bild",
    "gallery.filter.all": "Alla",
    "gallery.filter.food": "Mat",
    "gallery.filter.interior": "Interiör",
    "gallery.filter.team": "Team",
    "contact.badge": "Boka bord",
    "contact.subtitle": "Boka ditt bord och njut av en oförglömlig kväll",
    "contact.form.title": "Bokningsformulär",
    "contact.form.name": "Ditt namn",
    "contact.form.email": "E-post",
    "contact.form.phone": "Telefon",
    "contact.form.date": "Datum",
    "contact.form.time": "Tid",
    "contact.form.guests": "Antal gäster",
    "contact.form.guest": "Gäst",
    "contact.form.guestsPlural": "Gäster",
    "contact.form.submit": "Boka bord",
    "contact.form.selectPlaceholder": "Välj…",
    "contact.toast": "Bokning skickad! Vi kontaktar dig snart.",
    "contact.toastError": "Kunde inte skicka bokningen. Försök igen eller ring oss.",
    "events.form.title": "Boka event",
    "events.form.name": "Ditt namn",
    "events.form.email": "E-post",
    "events.form.phone": "Telefon",
    "events.form.date": "Datum",
    "events.form.time": "Tid",
    "events.form.guests": "Antal gäster",
    "events.form.type": "Typ av event",
    "events.form.type.private": "Privat middag",
    "events.form.type.birthday": "Födelsedag",
    "events.form.type.corporate": "Företag",
    "events.form.message": "Meddelande",
    "events.form.submit": "Skicka förfrågan",
    "events.form.messageEmpty": "(Inget meddelande)",
    "events.toast": "Eventförfrågan skickad! Vi kontaktar dig snart.",
    "events.toastError": "Kunde inte skicka förfrågan. Försök igen eller ring oss.",
    "contact.info.address.title": "Adress",
    "contact.info.address.content": "Calle Artilleros 3 03002 Alicante, Spanien",
    "contact.info.phone.title": "Telefon",
    "contact.info.phone.content": "+34 604 12 70 64",
    "contact.info.email.title": "E‑post",
    "contact.info.email.content": "lacueva708@gmail.com",
    "contact.info.hours.title": "Öppettider",
    "contact.info.hours.content":
      "Måndag–fredag: 18:00–01:30\nLördag–söndag: 14:00–01:30",
    "contact.map": "Karta",
    "footer.tagline": "Njut av god mat, mitt i stan",
    "footer.section.about": "Om oss",
    "footer.section.services": "Tjänster",
    "footer.section.contact": "Kontakt",
    "footer.link.history": "Vår historia",
    "footer.link.team": "Vår historia",
    "footer.link.careers": "Karriär",
    "footer.link.menu": "Meny",
    "footer.link.gallery": "Galleri",
    "footer.link.reservations": "Bokningar",
    "footer.link.events": "Event",
    "footer.link.privacy": "Integritetspolicy",
    "footer.link.terms": "Användarvillkor",
    "footer.rights": "Alla rättigheter förbehållna.",
    "ui.scrollToTop": "Till toppen",
    "ui.languageToggle": "Byt språk",
    "story.title": "Vår historia",
    "story.subtitle.part1":
      "Vi har varit bästa vänner i över tio år och har tidigare arbetat tillsammans fast i helt olika branscher. Det som verkligen förenar oss är vår gemensamma drivkraft att alltid göra saker bättre. När möjligheten kom att skapa en annorlunda, personlig och genuint rolig restaurang i Alicante så tvekade vi inte. För riktigt god mat handlar aldrig bara om det som ligger på tallriken. Det handlar om värme, stämning och att känna sig som hemma.",
    "story.subtitle.part2":
      "Som passionerade matskapare delar vi en särskild skandinavisk kärlek till såser, det som lyfter klassiska kött, fisk och desserträtter. Allt lagas från grunden med råvaror av högsta kvalitet. Det går inte att fuska med mat hos oss för när smak och skratt möts, då har man hittat det allra bästa receptet.",
  },
};

const getTranslation = (language: Language, key: string) => {
  return translations[language][key] ?? translations.en[key] ?? key;
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  /** English is always the default when the page loads (no persisted override). */
  const [language, setLanguage] = React.useState<Language>("en");

  const value = React.useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () =>
        setLanguage((current) =>
          current === "en" ? "es" : current === "es" ? "sv" : "en",
        ),
      t: (key: string) => getTranslation(language, key),
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
