"use client";

import * as React from "react";

type Language = "en" | "es" | "sv";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const LanguageContext = React.createContext<LanguageContextValue | null>(null);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.menu": "Menu",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "nav.story": "Our Story",
    "nav.book": "Book a Table",
    "nav.event": "Book an Event",
    "hero.badge": "Fine Dining Experience",
    "hero.title.line1": "Made with Taste &",
    "hero.title.line2": "Passion",
    "hero.subtitle":
      "Experience culinary excellence in an atmosphere of refined elegance",
    "hero.cta.menu": "View Menu",
    "hero.cta.about": "Learn More",
    "about.badge": "About Us",
    "about.story": "Our Story",
    "about.title.line1": "Where Taste Creates",
    "about.title.line2": "Memories",
    "about.paragraph1":
      "Welcome to our Swedish restaurant. Here, everything is prepared from scratch — with care, love, and deep respect for the ingredients. We serve Swedish cuisine of the highest quality, rich in flavor and tradition. And above all — with sauces at the heart of it all, just the way we believe it should be. Step inside and we’ll gladly tell you more. A warm welcome to you 💛",
    "about.paragraph2": "",
    "about.feature.experience.title": "Enjoy every bite",
    "about.feature.experience.desc": "",
    "about.feature.team.title": "Passionate team",
    "about.feature.team.desc": "",
    "about.feature.michelin.title": "Quality without pretension",
    "about.feature.michelin.desc": "",
    "story.title": "Our Story",
    "story.subtitle":
      "A simple idea, a warm table, and a love for honest food — that is how our story began.",
    "menu.badge": "Our Menu",
    "menu.title.line1": "Exquisite",
    "menu.title.line2": "Dishes",
    "menu.subtitle":
      "Discover our signature dishes, crafted with love and mastery",
    "menu.item.ribeye.name": "Ribeye Steak",
    "menu.item.ribeye.desc": "Premium beef with red wine sauce and truffle oil",
    "menu.item.pasta.name": "Seafood Pasta",
    "menu.item.pasta.desc": "Homemade pasta with tiger prawns, mussels and calamari",
    "menu.item.salmon.name": "Salmon Tartare",
    "menu.item.salmon.desc": "Fresh salmon tartare with avocado and caviar",
    "menu.item.chocolate.name": "Chocolate Mousse",
    "menu.item.chocolate.desc": "Belgian chocolate dessert with berry sauce",
    "menu.cta": "View Full Menu",
    "reviews.title": "Our rewies",
    "reviews.subtitle": "Guests share their experience with us.",
    "gallery.badge": "Gallery",
    "gallery.title.line1": "Take a Look at",
    "gallery.title.line2": "Our World",
    "gallery.subtitle": "Atmosphere, taste, and beauty in every frame",
    "gallery.filter.all": "All",
    "gallery.filter.food": "Food",
    "gallery.filter.interior": "Interior",
    "gallery.filter.team": "Team",
    "contact.badge": "Reserve a Table",
    "contact.title.line1": "We're Waiting for",
    "contact.title.line2": "You",
    "contact.subtitle": "Reserve your table and enjoy an unforgettable evening",
    "contact.form.title": "Reservation Form",
    "contact.form.name": "Your Name",
    "contact.form.phone": "Phone",
    "contact.form.date": "Date",
    "contact.form.time": "Time",
    "contact.form.guests": "Number of Guests",
    "contact.form.guest": "Guest",
    "contact.form.guestsPlural": "Guests",
    "contact.form.submit": "Reserve Table",
    "contact.toast": "Reservation submitted! We will contact you shortly.",
    "events.form.title": "Book an Event",
    "events.form.name": "Your Name",
    "events.form.phone": "Phone",
    "events.form.date": "Date",
    "events.form.time": "Time",
    "events.form.guests": "Number of Guests",
    "events.form.type": "Event Type",
    "events.form.type.private": "Private Dinner",
    "events.form.type.birthday": "Birthday",
    "events.form.type.corporate": "Corporate",
    "events.form.message": "Message",
    "events.form.submit": "Send Event Request",
    "events.toast": "Event request submitted! We will contact you shortly.",
    "contact.info.address.title": "Address",
    "contact.info.address.content": "Calle Artilleros 3 03002 Alicante, Spain",
    "contact.info.phone.title": "Phone",
    "contact.info.phone.content": "+34 604 12 70 64",
    "contact.info.email.title": "Email",
    "contact.info.email.content": "Lacueva708@gmail.com",
    "contact.info.hours.title": "Hours",
    "contact.info.hours.content": "Mon-Sun: 18:00 - 01:30",
    "contact.map": "Location Map",
    "footer.tagline": "Enjoy good food, right in the city.",
    "footer.section.about": "About",
    "footer.section.services": "Services",
    "footer.section.contact": "Contact",
    "footer.link.history": "History",
    "footer.link.team": "Team",
    "footer.link.careers": "Careers",
    "footer.link.menu": "Menu",
    "footer.link.reservations": "Reservations",
    "footer.link.events": "Events",
    "footer.link.privacy": "Privacy Policy",
    "footer.link.terms": "Terms of Service",
    "footer.rights": "All rights reserved.",
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Sobre",
    "nav.menu": "Menú",
    "nav.gallery": "Galería",
    "nav.contact": "Contacto",
    "nav.story": "Nuestra historia",
    "nav.book": "Reservar mesa",
    "nav.event": "Reservar evento",
    "hero.badge": "Experiencia de alta cocina",
    "hero.title.line1": "Donde el sabor se encuentra con",
    "hero.title.line2": "El arte",
    "hero.subtitle":
      "Vive la excelencia culinaria en un ambiente de elegancia refinada",
    "hero.cta.menu": "Ver menú",
    "hero.cta.about": "Saber más",
    "about.badge": "Sobre nosotros",
    "about.story": "Nuestra historia",
    "about.title.line1": "Donde el sabor crea",
    "about.title.line2": "Recuerdos",
    "about.paragraph1":
      "Creemos que la buena comida empieza con el cuidado. Ingredientes locales y frescos y ideas simples y pensadas se unen para crear platos hermosos, llenos de sabor y fáciles de disfrutar, inspirados en la sencillez y el equilibrio escandinavos.",
    "about.paragraph2":
      "Cada visita es un momento para bajar el ritmo, disfrutar del ambiente y sentirse cómodo. Un lugar para buen ánimo, buena comida y tiempo bien aprovechado.",
    "about.feature.experience.title": "Disfruta cada bocado",
    "about.feature.experience.desc": "",
    "about.feature.team.title": "Equipo apasionado",
    "about.feature.team.desc": "",
    "about.feature.michelin.title": "Calidad sin pretensiones",
    "about.feature.michelin.desc": "",
    "story.title": "Nuestra historia",
    "story.subtitle":
      "Una idea sencilla, una mesa cálida y el amor por la comida honesta — así comenzó nuestra historia.",
    "menu.badge": "Nuestro menú",
    "menu.title.line1": "Platos",
    "menu.title.line2": "Exquisitos",
    "menu.subtitle": "Descubre nuestros platos exclusivos, hechos con amor y maestría",
    "menu.item.ribeye.name": "Bistec Ribeye",
    "menu.item.ribeye.desc":
      "Carne premium con salsa de vino tinto y aceite de trufa",
    "menu.item.pasta.name": "Pasta de mariscos",
    "menu.item.pasta.desc":
      "Pasta casera con langostinos, mejillones y calamar",
    "menu.item.salmon.name": "Tartar de salmón",
    "menu.item.salmon.desc": "Salmón fresco con aguacate y caviar",
    "menu.item.chocolate.name": "Mousse de chocolate",
    "menu.item.chocolate.desc": "Postre belga con salsa de frutos rojos",
    "menu.cta": "Ver menú completo",
    "reviews.title": "Reseñas",
    "reviews.subtitle": "Nuestros clientes comparten su experiencia.",
    "gallery.badge": "Galería",
    "gallery.title.line1": "Mira",
    "gallery.title.line2": "Nuestro mundo",
    "gallery.subtitle": "Atmósfera, sabor y belleza en cada imagen",
    "gallery.filter.all": "Todo",
    "gallery.filter.food": "Comida",
    "gallery.filter.interior": "Interior",
    "gallery.filter.team": "Equipo",
    "contact.badge": "Reserva una mesa",
    "contact.title.line1": "Te estamos",
    "contact.title.line2": "Esperando",
    "contact.subtitle": "Reserva tu mesa y disfruta de una noche inolvidable",
    "contact.form.title": "Formulario de reserva",
    "contact.form.name": "Tu nombre",
    "contact.form.phone": "Teléfono",
    "contact.form.date": "Fecha",
    "contact.form.time": "Hora",
    "contact.form.guests": "Número de invitados",
    "contact.form.guest": "Invitado",
    "contact.form.guestsPlural": "Invitados",
    "contact.form.submit": "Reservar mesa",
    "contact.toast": "¡Reserva enviada! Nos pondremos en contacto pronto.",
    "events.form.title": "Reservar evento",
    "events.form.name": "Tu nombre",
    "events.form.phone": "Teléfono",
    "events.form.date": "Fecha",
    "events.form.time": "Hora",
    "events.form.guests": "Número de invitados",
    "events.form.type": "Tipo de evento",
    "events.form.type.private": "Cena privada",
    "events.form.type.birthday": "Cumpleaños",
    "events.form.type.corporate": "Corporativo",
    "events.form.message": "Mensaje",
    "events.form.submit": "Enviar solicitud",
    "events.toast": "¡Solicitud enviada! Nos pondremos en contacto pronto.",
    "contact.info.address.title": "Dirección",
    "contact.info.address.content": "Calle Artilleros 3 03002 Alicante, España",
    "contact.info.phone.title": "Teléfono",
    "contact.info.phone.content": "+34 604 12 70 64",
    "contact.info.email.title": "Correo",
    "contact.info.email.content": "Lacueva708@gmail.com",
    "contact.info.hours.title": "Horario",
    "contact.info.hours.content": "Lun-Dom: 18:00 - 01:30",
    "contact.map": "Mapa de ubicación",
    "footer.tagline": "Disfruta buena comida, justo en la ciudad.",
    "footer.section.about": "Sobre",
    "footer.section.services": "Servicios",
    "footer.section.contact": "Contacto",
    "footer.link.history": "Historia",
    "footer.link.team": "Equipo",
    "footer.link.careers": "Carreras",
    "footer.link.menu": "Menú",
    "footer.link.reservations": "Reservas",
    "footer.link.events": "Eventos",
    "footer.link.privacy": "Política de privacidad",
    "footer.link.terms": "Términos de servicio",
    "footer.rights": "Todos los derechos reservados.",
  },
  sv: {
    "nav.home": "Hem",
    "nav.about": "Om",
    "nav.menu": "Meny",
    "nav.gallery": "Galleri",
    "nav.contact": "Kontakt",
    "nav.story": "Vår historia",
    "nav.book": "Boka bord",
    "nav.event": "Boka event",
    "hero.badge": "Fine dining‑upplevelse",
    "hero.title.line1": "Skapat med smak &",
    "hero.title.line2": "Passion",
    "hero.subtitle":
      "Upplev kulinarisk excellens i en elegant atmosfär",
    "hero.cta.menu": "Se meny",
    "hero.cta.about": "Läs mer",
    "about.badge": "Om oss",
    "about.story": "Vår historia",
    "about.title.line1": "Där smaken skapar",
    "about.title.line2": "Minnen",
    "about.paragraph1":
      "Välkommen till vår svenska restaurang. Här lagas allt från grunden — med omsorg, kärlek och djup respekt för råvarorna. Vi serverar svensk mat av högsta kvalitet, rik på smak och tradition. Och framför allt — med såser i centrum, precis som vi tycker det ska vara. Kliv in så berättar vi gärna mer. Varmt välkommen 💛",
    "about.paragraph2": "",
    "about.feature.experience.title": "Njut av varje tugga",
    "about.feature.experience.desc": "",
    "about.feature.team.title": "Passionerat team",
    "about.feature.team.desc": "",
    "about.feature.michelin.title": "Kvalitet utan pretentioner",
    "about.feature.michelin.desc": "",
    "menu.badge": "Vår meny",
    "menu.title.line1": "Utsökta",
    "menu.title.line2": "Rätter",
    "menu.subtitle": "Upptäck våra signaturrätter, lagade med kärlek",
    "menu.item.ribeye.name": "Ribeye‑stek",
    "menu.item.ribeye.desc": "Premiumbiff med rödvinssås och tryffelolja",
    "menu.item.pasta.name": "Skaldjurspasta",
    "menu.item.pasta.desc": "Hemlagad pasta med räkor, musslor och bläckfisk",
    "menu.item.salmon.name": "Lax­tartar",
    "menu.item.salmon.desc": "Färsk lax med avokado och kaviar",
    "menu.item.chocolate.name": "Chokladmousse",
    "menu.item.chocolate.desc": "Belgisk dessert med bärsås",
    "menu.cta": "Se hela menyn",
    "reviews.title": "Omdömen",
    "reviews.subtitle": "Gäster delar sin upplevelse med oss.",
    "gallery.badge": "Galleri",
    "gallery.title.line1": "Ta en titt på",
    "gallery.title.line2": "Vår värld",
    "gallery.subtitle": "Atmosfär, smak och skönhet i varje bild",
    "gallery.filter.all": "Alla",
    "gallery.filter.food": "Mat",
    "gallery.filter.interior": "Interiör",
    "gallery.filter.team": "Team",
    "contact.badge": "Boka bord",
    "contact.title.line1": "Vi väntar på",
    "contact.title.line2": "Dig",
    "contact.subtitle": "Boka ditt bord och njut av en oförglömlig kväll",
    "contact.form.title": "Bokningsformulär",
    "contact.form.name": "Ditt namn",
    "contact.form.phone": "Telefon",
    "contact.form.date": "Datum",
    "contact.form.time": "Tid",
    "contact.form.guests": "Antal gäster",
    "contact.form.guest": "Gäst",
    "contact.form.guestsPlural": "Gäster",
    "contact.form.submit": "Boka bord",
    "contact.toast": "Bokning skickad! Vi kontaktar dig snart.",
    "events.form.title": "Boka event",
    "events.form.name": "Ditt namn",
    "events.form.phone": "Telefon",
    "events.form.date": "Datum",
    "events.form.time": "Tid",
    "events.form.guests": "Antal gäster",
    "events.form.type": "Typ av event",
    "events.form.type.private": "Privat middag",
    "events.form.type.birthday": "Födelsedag",
    "events.form.type.corporate": "Företag",
    "events.form.message": "Meddelande",
    "events.form.submit": "Skicka förfrågan",
    "events.toast": "Eventförfrågan skickad! Vi kontaktar dig snart.",
    "contact.info.address.title": "Adress",
    "contact.info.address.content": "Calle Artilleros 3 03002 Alicante, Spanien",
    "contact.info.phone.title": "Telefon",
    "contact.info.phone.content": "+34 604 12 70 64",
    "contact.info.email.title": "E‑post",
    "contact.info.email.content": "Lacueva708@gmail.com",
    "contact.info.hours.title": "Öppettider",
    "contact.info.hours.content": "Mån–Sön: 18:00 – 01:30",
    "contact.map": "Karta",
    "footer.tagline": "Njut av god mat, mitt i stan.",
    "footer.section.about": "Om",
    "footer.section.services": "Tjänster",
    "footer.section.contact": "Kontakt",
    "footer.link.history": "Historia",
    "footer.link.team": "Team",
    "footer.link.careers": "Karriär",
    "footer.link.menu": "Meny",
    "footer.link.reservations": "Bokningar",
    "footer.link.events": "Event",
    "footer.link.privacy": "Integritetspolicy",
    "footer.link.terms": "Användarvillkor",
    "footer.rights": "Alla rättigheter förbehållna.",
    "story.title": "Vår historia",
    "story.subtitle":
      "En enkel idé, ett varmt bord och kärlek till ärlig mat — så började vår historia.",
  },
};

const getTranslation = (language: Language, key: string) => {
  return translations[language][key] ?? translations.en[key] ?? key;
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = React.useState<Language>("en");

  React.useEffect(() => {
    const saved = window.localStorage.getItem("language");
    if (saved === "en" || saved === "es" || saved === "sv") {
      setLanguage(saved);
    }
  }, []);

  React.useEffect(() => {
    window.localStorage.setItem("language", language);
  }, [language]);

  const value = React.useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () =>
        setLanguage((current) =>
          current === "en" ? "es" : current === "es" ? "sv" : "en",
        ),
      t: (key: string) => getTranslation(language, key),
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
